# -*- coding: utf-8 -*-
"""Prompt Engineering With LangChai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbdhU7MaWOFcFtZfHI3X5oCCi6euNouu

# **The Begain**
"""

!pip install wikipedia
!pip install -U langchain-community
!pip install -U langchain-core
!pip install faiss-cpu
!pip install langchain-google-genai
!pip install cohere
!pip install langchain
!pip install -U bitsandbytes langchain_huggingface
!pip install langchain_chroma
!pip install nltk
!pip install pypdf
!pip install unstructured
!pip install transformers sentencepiece
!pip install tiktoken

!pip install -U langchain
!pip install -U langchain_google_genai

from dotenv import dotenv_values
env_values = dotenv_values("./app.env")

gemini_api_key = env_values['GEMINI_API_KEY']

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage , AIMessage , SystemMessage

chat = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash-lite",
    temperature = 0.7 ,
    google_api_key = gemini_api_key
)

print(gemini_api_key)

"""# **2. Hugging Face Open Sourced Models**"""

from transformers import LlamaTokenizer ,  LlamaForCausalLM ,  GenerationConfig, pipeline, BitsAndBytesConfig
import torch
from langchain_huggingface.llms import HuggingFacePipeline

model_id = "h2oai/h2ogpt-gm-oasst1-en-2048-open-llama-3b"
tokenizer = LlamaTokenizer.from_pretrained(model_id)
base_model = LlamaForCausalLM.from_pretrained(model_id,
                                              load_in_8bit=True,
                                              device_map='auto')

hf_pipeline = pipeline('text-generation',
                       model=base_model,
                       tokenizer=tokenizer)

llm = HuggingFacePipeline(pipeline=hf_pipeline)

prompt = """ Below is an intruction that describes a task. write a response that appropriately completes the request.
### Instruction:
[INSTRUCTION]
tell me 2 ways to lose weight

Answer:
""".strip()

print(llm.invoke(prompt , max_new_tokens=265))

"""# **3. API Based Language Models**"""

!pip install -U langchain
!pip install -U langchain_google_genai

from dotenv import dotenv_values
env_values = dotenv_values("./app.env")

gemini_api_key = env_values['GEMINI_API_KEY']

from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-lite",
      google_api_key=gemini_api_key,
    temperature=0.7
)

prompt1 = """
tell me 2 ways to lose weight
""".strip()

print(llm.invoke(prompt1))

response = llm.invoke(prompt)
print(response.text.strip())

#clculate tokens
print(response.usage_metadata)

from langchain_core.prompts import PromptTemplate
user_subject = "Linear algebra"
user_language = "arabic"
string_prompt = PromptTemplate(
    template = "explain {subject} like i am 5 , write the answer in {language}",
    input_variables = ['subject' , 'language']
)
prompt = string_prompt.format(subject = user_subject , language = user_language)
response = llm.invoke(prompt)
print(response.text.strip())

print(prompt)

string_prompt

"""# **5. LangChain Chat Schema**

# **5.1 Base Conversation**
"""

import google.generativeai as genai
genai.configure(api_key = gemini_api_key)

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage , AIMessage , SystemMessage

chat = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash-lite",
    temperature = 0.7 ,
    google_api_key = gemini_api_key
)

base_conversation = [
    SystemMessage(content="You are a chief , you , want to ask me some things to find out my favorite dish"),
    AIMessage(content="Where are you from?"),
    HumanMessage(content="Egypt"),
    AIMessage (content="Do you like spicy food?"),
    HumanMessage (content="Not too much"),
    AIMessage (content="Do you suffer from diabetes?"),
    HumanMessage (content="yes"),

]
response = chat.invoke(base_conversation)
print(response.content.strip())

base_conversation = [
    SystemMessage(content="You are a chief, you want to ask me some things to find out my favorite dish"),
    HumanMessage(content="Hello Chief!") # Add an initial HumanMessage)
]
response = None
for i in range(3):
  response = chat.invoke(base_conversation)
  print("AI" , response.content.strip())
  base_conversation.append(response)
  user_response = HumanMessage(content= input("Tou: "))
  base_conversation.append(user_response)

base_conversation

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage , SystemMessage , AIMessage
from langchain import chat_models

chat =ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite",
                             temperature = 0.7 ,
                             google_api_key = gemini_api_key)

system_context = SystemMessage(content="You are a cyber security engineer, your company coworkers are not profissional and they may ask you for any security problems they may face")
user_message = HumanMessage(content='i just clicked on a malicous link')
response = chat.invoke([system_context, user_message])
print(response.content)

"""# **5.2 Basic FewShots**"""

demo_message = """
Country Name: Egypt | Capital Name: Cairo
Country Name: Saudi Arabia | Capital Name: Riyadh
Country Name: Singapore | Capital Name: Singapore
Country Name: Armenia |
""".strip()

from langchain_google_genai import ChatGoogleGenerativeAI
chat = ChatGoogleGenerativeAI(
    model = 'gemini-2.5-flash-lite',
    temperature = 0.7,
    google_api_key = gemini_api_key
)

response = chat.invoke([HumanMessage(content=demo_message)])
print(response.content)

"""# **5.3 Fewshot using LangChain Prompt Template**"""

from langchain_core.prompts import FewShotPromptTemplate
from langchain_core.prompts import PromptTemplate

demo_template = PromptTemplate(
    template = "Country Name: {country} | Capital Name:{capital}",
    input_variables = ['country','capital']
)

examples = [
    {'country': 'Egypt', 'capital': 'Cairo'},
    {'country': 'Saudi Arabia', 'capital': 'Riyadh'},
    {'country': 'Singapore', 'capital': 'Singapore'}
]

prompt = FewShotPromptTemplate(
    example_prompt = demo_template,
    examples = examples,
    suffix = "Country Name: {country} |",
    input_variables =['country']
)

user_country = 'Austeria'
message = prompt.format(country = user_country)
print(message)

print(chat.invoke([HumanMessage(content=message)]))

message = "What is the ingredients to cook a pizza?"
response =chat.invoke(message)
print(response.content)

"""# **6. Custom Output Parser**

# **6.1 CommaSeparatedListOutputParser**
"""

from langchain_core.output_parsers import CommaSeparatedListOutputParser
from langchain_core.prompts import PromptTemplate

output_parser = CommaSeparatedListOutputParser()
format_instructions = output_parser.get_format_instructions()

prompt = PromptTemplate(
    template="List three popular {type} plates,\n{format_instructions}",
    input_variables=["type"],
    partial_variables={"format_instructions": format_instructions}
)

demo_message = prompt.format(type='arabian')

response = chat.invoke(demo_message).text.strip()
output = output_parser.parse(response)
print(output)

type(output)

"""# **6.5 Your custom (format_instructions)**"""

from langchain_core.output_parsers import CommaSeparatedListOutputParser
from langchain_core.prompts import PromptTemplate

output_parser = CommaSeparatedListOutputParser()
format_instructions = output_parser.get_format_instructions()

format_instructions = "Replay with a datatime format DD/MM/YYYY like '24/05/2002'."
prompt = PromptTemplate(
    template = 'When was {person} born? .\n{format_instructions}',
    input_variables = ['person','format_instructions']
)

message = prompt.format(person = 'Abdel Fatah EL Sisi' , format_instructions= format_instructions)
print(chat.invoke("The President Abdel Fatah EL Sisi was born in " + message).text.strip())

"""# Example"""

from langchain_core.output_parsers import CommaSeparatedListOutputParser
from langchain_core.prompts import PromptTemplate

output_parser_1 = CommaSeparatedListOutputParser()
format_instructions_1 = output_parser.get_format_instructions()

format_instructions_1 = "Replay with a datatime format {person} was born in DD/MM/YYYY like 'mahdi was born in 24/05/2002'."
prompt = PromptTemplate(
    template = "when was {person} born? .\n{format_instructions}",
    input_variables = ['person', 'format_instructions']
)
message_1 = prompt.format(person = "El Sheakh El Shaarawy" , format_instructions  = format_instructions)
print(chat.invoke(message_1).text.strip())

"""# **6.6 PyDantic**"""

from pydantic import BaseModel , Field
from typing import List
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import PromptTemplate

class Plate(BaseModel):
  plate_name: str = Field(description="name of the plate")
  ingredients: List[str] = Field(description="list of names of the ingredients")

parser = PydanticOutputParser(pydantic_object=Plate)

format_instructions = parser.get_format_instructions()

prompt = PromptTemplate(
    template = "Answer the query.\n{plate_name}\n{format_instructions}",
    input_variables =['plate_name'],
    partial_variables={"format_instructions":format_instructions}
)

plate_name ="shawerma"
message = prompt.format(plate_name=plate_name)
response = chat.invoke(message).text.strip()
output = parser.parse(response)

print(format_instructions)

print(message)

print(response)

print(output)

output.plate_name

output.ingredients

"""#7. Conversation Buffer (Memory)

# **7.1 Basic Memory (Conversation Buffer Memory)**
"""

message_1 = "list 3 places to visit in paris"
response = chat.invoke(message_1).text.strip()
print(response)

message_2= "which one of them has a lake view?"
response = chat.invoke(message_2).text.strip()
print(response)

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash-lite",
    google_api_key = gemini_api_key,
    temperature = 0.7
)

# 7.1 Basic Memory (Conversation Buffer Memory)


from langchain_core.chat_history import InMemoryChatMessageHistory
from langchain_core.runnables import RunnableWithMessageHistory

store ={}
def get_session_history(session_id: str) -> InMemoryChatMessageHistory:
  if session_id not in store:
    store[session_id] = InMemoryChatMessageHistory()
  return store[session_id]

chain = RunnableWithMessageHistory(llm , get_session_history)
response = chain.invoke(
    "list 3 places to visit in paris" ,
    config={"configurable" : {"session_id":"1"}}


)
print(response.content)
print("*"*30)
response = chain.invoke(
    "which one of the has a lake view?",
    config = {"configurable":{"session_id":"1"}},
)
print(response.content)

# Print all conversation messages
history = store["1"]  # same session_id you used above
print("\nFull conversation:")
print("=" * 40)
for msg in history.messages:
    role = "User" if msg.type == "human" else "AI"
    print(f"{role}: {msg.content}\n")

history.messages

store

store.clear()

store

"""# **Example**"""

from langchain_core.chat_history import InMemoryChatMessageHistory
from langchain_core.runnables import RunnableWithMessageHistory

store ={}

def get_session_history1(session_id:str) -> InMemoryChatMessageHistory:
  if session_id not in store:
    store[session_id] = InMemoryChatMessageHistory()
  return store[session_id]

chain = RunnableWithMessageHistory(llm  , get_session_history1)
response = chain.invoke(
    "list 3 places to visit in Egypt",
    config ={"configurable" : {"session_id" : "1"}},
)
print(response.content)
print("*"*30)
response = chain.invoke(
    "which one of the has the greatest history?",
    config = {"configurable" : {"session_id" : "1"}},
)

print(response.content)

# Print all conversation messages
history = store["1"]  # same session_id you used above
print("\nFull conversation:")
print("=" * 40)
for msg in history.messages:
    role = "User" if msg.type == "human" else "AI"
    print(f"{role}: {msg.content}\n")

history.messages

store

store.clear()

store

"""# 7.2 Conversation Buffer Window Memory

# Keeps the last n turns of the conversation. Drops the oldest turn when the buffer is full.
"""

from langchain_core.messages import trim_messages

selected_messages = trim_messages(
    history.messages,
    token_counter=len,  # <-- len will simply count the number of messages rather than tokens
    max_tokens=3,  # <-- allow up to 2 messages.
    strategy="last",
    # Most chat models expect that chat history starts with either:
    # (1) a HumanMessage or
    # (2) a SystemMessage followed by a HumanMessage
    # start_on="human" makes sure we produce a valid chat history
    start_on="human",
    # Usually, we want to keep the SystemMessage
    # if it's present in the original history.
    # The SystemMessage has special instructions for the model.
    include_system=True,
    allow_partial=False,
)

for msg in selected_messages:
    msg.pretty_print()

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, AIMessage
from langgraph.graph import StateGraph, END

gemini_api_key = gemini_api_key

model = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-lite",
    google_api_key=gemini_api_key,
    temperature=0.7,
)

# --- STEP 1: Define the state ---
from typing import List, TypedDict

class State(TypedDict):
    messages: List
    summary: str

# --- STEP 2: Define your summarization reducer ---
def summarize_conversation(state: State):
    summary = state.get("summary", "")
    if summary:
        summary_message = (
            f"This is a summary of the conversation so far: {summary}\n\n"
            "Extend the summary by considering the new messages above."
        )
    else:
        summary_message = "Create a summary of the conversation above."

    # Add the summarization instruction to the messages
    messages = state["messages"] + [HumanMessage(content=summary_message)]
    response = model.invoke(messages)

    # Keep the last 2 messages and store new summary
    return {
        "summary": response.content,
        "messages": state["messages"][-2:]  # keep short memory
    }

# --- STEP 3: Define the main conversation node ---
def chat_node(state: State):
    response = model.invoke(state["messages"])
    return {"messages": state["messages"] + [response]}

# --- STEP 4: Build the graph ---
graph = StateGraph(State)

graph.add_node("chat", chat_node)
graph.add_node("summarize", summarize_conversation)
graph.add_edge("chat", "summarize")
graph.add_edge("summarize", END)

graph.set_entry_point("chat")

app = graph.compile()

# --- STEP 5: Run the conversation ---
state = {"messages": [HumanMessage(content="List 3 places to visit in Paris.")], "summary": ""}

state = app.invoke(state)
print("Bot:", state["messages"][-1].content)
print("Summary:", state["summary"])

# Continue conversation
state["messages"].append(HumanMessage(content="Which one of them has a lake view?"))
state = app.invoke(state)

print("\nBot:", state["messages"][-1].content)
print("Updated summary:", state["summary"])

""" ## 7.5 Save messages into File"""

from langchain_core.messages import AIMessage , HumanMessage , messages_to_dict , messages_from_dict
import json

messages = [
    HumanMessage(content = "Hello"),
    AIMessage(content="Hi There! How can i help you?"),
    HumanMessage(content="Tell me a joke."),
    AIMessage(content="Why did the computer go to art school? Because it had a lot of cache!")
]

# Convert messages to dictionary format
messages_dict = messages_to_dict(messages)

# Save to a json file
with open("Conversation-memory.json","w") as f:
  json.dump(messages_dict , f, indent=2 , ensure_ascii=False)

print("Conversation saved to conversation-memory.json")

"""# 7.6 Load Saved Messages into history"""

from langchain_core.messages import messages_from_dict
from langchain_community.chat_message_histories import ChatMessageHistory
import json

# Load From Json
with open("Conversation-memory.json" , "r") as f:
  dicts = json.load(f)

# Convert to Message objects
messages = messages_from_dict(dicts)

# Create ChatMessageHistory and load them
history = ChatMessageHistory()
for msg in messages:
    history.add_message(msg)

print("Loaded history:")
for m in history.messages:
    print(f"{m.type}: {m.content}")

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.runnables.history import RunnableWithMessageHistory

chat = ChatGoogleGenerativeAI(
      model = "gemini-2.5-flash-lite",
      temperature = 0.7 ,
      google_api_key = gemini_api_key
)
store = {"session_1": history}  # reuse loaded history

def get_session_history(session_id: str):
    if session_id not in store:
        store[session_id] = ChatMessageHistory()
    return store[session_id]

chain = RunnableWithMessageHistory(chat, get_session_history)

response = chain.invoke(
    "as an egyptian, which place from the 3 i will like most?",
    config={"configurable": {"session_id": "session_1"}},
)

print(response.content)

"""#8. Loaders

##8.1 Data Frame Loader
"""

!wget -O youtube-sub.csv https://raw.githubusercontent.com/petlja/jupyterBookSrCyr/master/podaci/Top%2025%20YouTubers.csv

import pandas as pd
df = pd.read_csv("./youtube-sub.csv" , sep=",")

df.head()

df = df[["NAME","VIDEOS","SUBSCRIBERS","VIEWES"]]
df.head()

from langchain_community.document_loaders import DataFrameLoader
llm_loader = DataFrameLoader(df , page_content_column="NAME")

llm_data = llm_loader.load()

llm_data

llm_data[5].dict()

"""#8.2 URL Loader"""

from langchain_community.document_loaders import UnstructuredURLLoader

urls = [
    "https://www.geeksforgeeks.org/courses/data-science-live",
    "https://prayertimes3.today/egypt-eg/alexandria-158.html"
]

llm_loader = UnstructuredURLLoader(urls = urls)
llm_data = llm_loader.load()

llm_data

"""#8.3 Wikipedia Loader"""

from langchain_community.document_loaders import WikipediaLoader
query = "Mohamed Salah"
llm_data = WikipediaLoader(
    query = query,
    load_max_docs = 3,
    doc_content_chars_max = 20_000).load()

len(llm_data)

llm_data[0].page_content

llm_data[0].metadata

"""#8.4 PDF Loader"""

!wget -O coc_deepseek.pdf https://arxiv.org/pdf/2510.18234

from langchain_community.document_loaders import PyPDFLoader
llm_loader = PyPDFLoader("./coc_deepseek.pdf")
pages = llm_loader.load_and_split()

len(pages)

pages[6]

pages[6].page_content

pages[6].metadata

"""#8.6 Directories Loader (txt)"""

from langchain_community.document_loaders import DirectoryLoader
llm_loader = DirectoryLoader("./md-data",
                             glob = "*.txt",
                             show_progress = True)

llm_data = llm_loader.load()

llm_data

"""#8.7 Directories Loader (PDF)"""

from langchain_community.document_loaders import PyPDFDirectoryLoader
llm_loader = PyPDFDirectoryLoader("papers")
llm_data = llm_loader.load()

print(len(llm_data))
print(llm_data[2].page_content[:30])
print(llm_data[3].metadata)

"""#9. Text Splitter"""

# Example
from langchain_community.document_loaders import WikipediaLoader

query_1 = "Nikola Tesla"
docs_1 = WikipediaLoader(
    query = query_1,
    load_max_docs = 1,
    doc_content_chars_max = 20_000).load()

document_1 = docs_1[0].page_content

query_2 = "Thomas Edison"
docs_2 = WikipediaLoader(
    query = query_2,
    load_max_docs = 1,
    doc_content_chars_max = 20_000
).load()
document_2 = docs_2[0].page_content


documents = [document_1 , document_2]
metadatas =[{"document":query_1},{"document":query_2}]

len(docs_1)

print(docs_1[0].page_content)

"""#9.1 CharacterTextSplitter"""

from langchain_text_splitters import CharacterTextSplitter

text_spliter = CharacterTextSplitter(
    separator ="",
    chunk_size = 100,
    length_function = len,
    chunk_overlap = 20
)

normal_chunks = text_spliter.create_documents(documents, metadatas=metadatas)

len(normal_chunks)

normal_chunks[4]

len(normal_chunks[300].page_content)

## Without overLab
text_spliter = CharacterTextSplitter(
    separator = "",
    chunk_size = 100 ,
    length_function = len,
    chunk_overlap = 0,
)

normal_chunks1 = text_spliter.create_documents(documents , metadatas=metadatas)

normal_chunks1[1].page_content

"""#9.2 NLTK"""

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

from langchain_text_splitters import NLTKTextSplitter

text_splitter = NLTKTextSplitter(
    chunk_size = 300,
    chunk_overlap = 50
)

nltk_chunks = text_splitter.create_documents(documents , metadatas = metadatas)

len(nltk_chunks)

print(nltk_chunks[3].page_content)

print(nltk_chunks[3].metadata)

"""#9.3 TikToken"""

from langchain_text_splitters import TokenTextSplitter
text_splitter = TokenTextSplitter(
    model_name = "gpt-4o-mini",
    chunk_size=100,
    chunk_overlap=20,
)

token_chunks = text_splitter.create_documents(
    documents , metadatas= metadatas
)

len(token_chunks)

token_chunks[5].page_content

"""#9.4 Transformers Tokens"""

from transformers import AutoTokenizer
model_id = "stabilityai/stablelm-tuned-alpha-3b"
tokenizer = AutoTokenizer.from_pretrained(model_id)

from langchain_text_splitters import CharacterTextSplitter
text_splitter = CharacterTextSplitter.from_huggingface_tokenizer(
    tokenizer,
    chunk_size = 400,
    chunk_overlap = 0,
)

chunks = text_splitter.create_documents(documents, metadatas=metadatas)

chunks[0].page_content

"""#. **Revision**"""

from langchain_community.document_loaders import WikipediaLoader
query_1 = "Mohamed salah"
query_2 = "Mohamed Aboutrika"


#=========================
docs_1 = WikipediaLoader(
    query = query_1,
    load_max_docs = 1,
    doc_content_chars_max= 20_000
).load()

text_documents_1 = docs_1[0].page_content

#===========================
docs_2 = WikipediaLoader(
    query = query_2 ,
    load_max_docs = 1 ,
    doc_content_chars_max = 20_000
).load()

text_documents_2  = docs_2[0].page_content

documents = [text_documents_1, text_documents_2]
metadatas = [{"document" : query_1} , {"document":query_2}]

documents[0]

documents[1]

from langchain_text_splitters import NLTKTextSplitter
import nltk
nltk.download("punkt")
nltk.download('punkt_tab')

text_splitter = NLTKTextSplitter(
    chunk_size = 300,
    chunk_overlap = 50
)

token_chunks = text_splitter.create_documents(documents , metadatas=metadatas)

len(token_chunks)

token_chunks[5]

"""#10. Embeddings

##10.1 Embedding with Gemini API
"""

from langchain_google_genai import GoogleGenerativeAIEmbeddings
from dotenv import dotenv_values
env_values = dotenv_values("./app.env")
gemini_api_key = env_values["GEMINI_API_KEY"]

embedding_llm = GoogleGenerativeAIEmbeddings(
    model = "models/text-embedding-004",
     google_api_key = gemini_api_key
)

vector = embedding_llm.embed_query("Hello World")

vector[:5]

# embed multiple string at once
vectors = embedding_llm.embed_documents(
    [
        "Today is Monday",
        "Today is Tuesday",
        "Today is April Fools day"
    ]
)
len(vectors) , len(vectors[0])

"""##Embedding Source Data"""

docs_1[0]

token_chunks[5]

docs_text = [chunk.page_content for chunk in token_chunks]

docs_embeddings = embedding_llm.embed_documents(docs_text)

docs_text[5]

"""##Query Embedding"""

query = "Can You Tell me Which is the frist Team That Mohammed Salah Played For"

query_embedding = embedding_llm.embed_query(query)
query_embedding[:5]

"""##10.2 Embedding with HuggingFace"""

from sentence_transformers import SentenceTransformer
model =  SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

query_embeddings = model.encode(query)

vector[:5]

"""##10.3 Embedding with Cohere"""

from dotenv import dotenv_values
env_values = dotenv_values("app.env")
cohere_api_key = env_values['COHERE_API_KEY']

from langchain_community.embeddings.cohere import CohereEmbeddings
embedding_llm = CohereEmbeddings(cohere_api_key = cohere_api_key , user_agent = "langchain")

token_chunks[4]

## Source Data
docs_text = [ chunk.page_content for chunk in token_chunks]
docs_embeddings = embedding_llm.embed_documents(docs_text)

docs_text[4]

#Query Embedding
query_text = "How many  and which clubs that salah played for it?"
query_embeddings = embedding_llm.embed_query(query_text)

print(query_embeddings)

len(docs_embeddings[2])

"""#11. Vector Database"""

from langchain_community.document_loaders import WikipediaLoader
from langchain_text_splitters import NLTKTextSplitter
import nltk
nltk.download('punkt')
from langchain_google_genai import GoogleGenerativeAIEmbeddings

query = "Nikola Tesla"

docs = WikipediaLoader(
    query = query,
    load_max_docs = 1,
    doc_content_chars_max = 20_000
).load()

document_1 = docs[0].page_content

document_1

text_splitter = NLTKTextSplitter(
    chunk_size = 300,
    chunk_overlap = 50
)


token_chunks = text_splitter.create_documents(
    [document_1],
    metadatas = [{"document" : query}]
)

embedding_llm = GoogleGenerativeAIEmbeddings(
    google_api_key = gemini_api_key ,
    model = "models/text-embedding-004"
)

"""##Vector Stores | FAISS"""

from langchain_community.vectorstores import FAISS
vector_db = FAISS.from_documents(token_chunks , embedding_llm)

query_text = "In which year did Tesla's fathre die? "
similar_docs = vector_db.similarity_search(query_text)

similar_docs[0]

"""##Vector Stores | Chroma"""

from langchain_community.vectorstores import Chroma

# Store text documents as vector
save_to_dir = "/content/wiki_chroma_db"

docs_ids = list(range(len(token_chunks)))
docs_ids = [ str(d) for d in docs_ids]

vector_db = Chroma.from_documents(
    token_chunks ,
    embedding_llm ,
    persist_directory = save_to_dir,
    ids = docs_ids
)

# Search for most similarity document to a query

query_text = "In which year did Tesla's fathre die?"

similar_docs = vector_db.similarity_search(
    query_text ,
    k =5,
    filter = {'document':'Nikola Tesla'}
)

## Save to disk
vector_db.persist()

## Load from disk
load_from_dir = '/content/wiki_chroma_db'

load_vector_db = Chroma(
    persist_directory = load_from_dir ,
    embedding_function = embedding_llm
)

## Search for most similar document to a query
query_text = "In which year did Tesla's fathre die?"

similar_docs = load_vector_db.similarity_search(
    query_text ,
    k =5,
    filter = {'document' : 'Nikola Tesla'}
)

print( similar_docs[0] )

"""#Example Source Data (RAG test case)"""

from langchain_community.document_loaders import WikipediaLoader
from langchain_text_splitters import NLTKTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_chroma import Chroma
import nltk
nltk.download('punkt')

#load document
query = 'Nikola Tesla'
docs = WikipediaLoader(
    query = query,
    load_max_docs = 1,
    doc_content_chars_max =20_000
).load()

document = docs[0].page_content
metadatas = [{"document" : query}]

text_splitter = NLTKTextSplitter(chunk_size=300 ,
                                 chunk_overlap = 50
)

token_chunks = text_splitter.create_documents([document] ,
                                              metadatas = metadatas)

embedding_llm = GoogleGenerativeAIEmbeddings(model="models/text-embedding-004",
                                              google_api_key = gemini_api_key)

save_to_dir = "/content/Wiki_chroma_db"
vector_db = Chroma.from_documents(
    token_chunks ,
    embedding_llm ,
    persist_directory = save_to_dir
)

document

"""#12. QnA Chain"""

from langchain_core.prompts import PromptTemplate
from langchain_core.prompts import ChatPromptTemplate

prompt = PromptTemplate(
    input_variables = ["context" ,"question"],
    template = """
    Use the following context to answer the question.
    if the answer is not contained in the context, say "No Answer is Available"

    Context:
    {context}

    Question:
    {question}

    Answer
    """
)

question = "when was Nicola Tesla born?"

similar_docs = vector_db.similarity_search(question , k = 3)

def stuff_chain(docs , question):
  context = "\n\n".join(doc.page_content for doc in docs)
  return chat.invoke(prompt.format(context = context , question = question))

answer = stuff_chain(similar_docs, question)
print(answer.text.strip())

question="what is the favourite food for Nicola Tesla"
answer = stuff_chain(similar_docs, question)
print(answer.text.strip())

"""## 12.2 MapReduce chain (LCEL 2025)




"""

map_prompt = PromptTemplate(
    input_variables =['document'],
    template = """
    You are given a document chunk. summarize the core meaning consisely.

    Document:
    {document}

    Summary:
    """
)

reduce_prompt = PromptTemplate(
    input_variables=["summaries","question"],
    template="""
    You are given multiple summaries. use them to answer the question
    if the answer is not contained in the summaries, say "No Answer is Available"
    Summaries:
   {summaries}

   Question:
   {question}

   Answer:
    """
)

def map_reduce_chain(docs, question):
  summaries = []
  for doc in docs:
    summaries.append(chat.invoke(map_prompt.format(document=doc.page_content)).text.strip())
  return chat.invoke(reduce_prompt.format(summaries = summaries , question = question)).text.strip()

question = "what did Tesla invent?"

similar_docs = vector_db.similarity_search(question, k=3)

answer = map_reduce_chain(similar_docs, question)
print(answer)

"""## 12.3 Refine chain (LCEL 2025)

---


"""

initial_prompt = PromptTemplate(
    input_variables = ["document", "question"],
    template="""
    Answer the following question using the provided document,

    Document:
    {document}

    Question:
    {question}

    Answer:
    """
)

refine_prompt = PromptTemplate(
    input_variables = ["existing_answer", "document", "question"],
    template="""
    We have an exsiting answer:
    {existing_answer}

    Here is new information from another document:
    {document}

    Question:
    {question}

    Refine the existing answer to include this ew information
    If the new document does not add anything, keep the answer unchanged

    Refined Answer:
    """
)

def refine_chain(docs, question):
  # initial step (given best match doc)
  answer = chat.invoke(initial_prompt.format(document=docs[0].page_content, question=question)).text.strip()
  # refine step (given rest of docs)
  for doc in docs[1:]:
    answer =  chat.invoke(refine_prompt.format(existing_answer=answer,
                                                        document=doc.page_content,
                                                        question=question)).text.strip()
  return answer

question = "what did Tesla invent?"

similar_docs = vector_db.similarity_search(question, k=2)

answer = refine_chain(similar_docs, question)
print(answer)

